# Generated by Django 5.1.6 on 2025-02-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOR", "Normal"),
                    ("BOR", "Borrowed"),
                    ("BOK", "Booked"),
                    ("WOF", "Written Off"),
                ],
                default="NOR",
                max_length=3,
            ),
        ),
    ]
