# Generated by Django 5.1.6 on 2025-02-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bundle_id",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Bundle ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOR", "Normal"),
                            ("BOR", "Borrowed"),
                            ("PRE", "Preparing"),
                        ],
                        default="NOR",
                        max_length=3,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("time_added", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "books",
                    models.ManyToManyField(
                        blank=True, related_name="bundles", to="books.book"
                    ),
                ),
            ],
            options={
                "ordering": ["bundle_id"],
            },
        ),
    ]
