# Generated by Django 5.1.6 on 2025-02-26 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0003_alter_book_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bundle_id",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Bundle ID must be a letter followed by numbers (e.g., A12)",
                                regex="^[A-Z]\\d+$",
                            )
                        ],
                        verbose_name="Bundle ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOR", "Normal"),
                            ("BOR", "Borrowed"),
                            ("PRE", "Preparing"),
                        ],
                        default="NOR",
                        max_length=3,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("time_added", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "books",
                    models.ManyToManyField(
                        blank=True, related_name="bundles", to="books.book"
                    ),
                ),
            ],
            options={
                "ordering": ["bundle_id"],
            },
        ),
    ]
