# Generated by Django 5.1.6 on 2025-02-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bundle",
            name="bundle_id",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="Bundle ID"
            ),
        ),
    ]
