# Generated by Django 5.1.6 on 2025-02-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bundle",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOR", "Normal"),
                    ("BOR", "Borrowed"),
                    ("PRE", "Preparing"),
                    ("LOS", "Lost"),
                ],
                default="NOR",
                max_length=3,
            ),
        ),
    ]
