# Generated by Django 5.1.6 on 2025-02-27 07:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_status"),
        ("bundles", "0002_alter_bundle_status"),
        ("circulation", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BorrowRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACT", "Active"),
                            ("RET", "Returned"),
                            ("OVD", "Overdue"),
                            ("LOS", "Lost"),
                        ],
                        default="ACT",
                        max_length=3,
                    ),
                ),
                (
                    "borrowed_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("due_date", models.DateTimeField()),
                ("returned_date", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="borrow_records",
                        to="books.book",
                    ),
                ),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="borrow_records",
                        to="users.profile",
                    ),
                ),
                (
                    "bundle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="borrow_records",
                        to="bundles.bundle",
                    ),
                ),
            ],
            options={
                "ordering": ["-borrowed_date"],
                "indexes": [
                    models.Index(
                        fields=["status", "-borrowed_date"],
                        name="circulation_status_0f4c07_idx",
                    ),
                    models.Index(
                        fields=["borrower", "status"],
                        name="circulation_borrowe_376889_idx",
                    ),
                    models.Index(
                        fields=["book", "status"], name="circulation_book_id_89fd32_idx"
                    ),
                    models.Index(
                        fields=["bundle", "status"],
                        name="circulation_bundle__1755fc_idx",
                    ),
                ],
            },
        ),
    ]
